repos:
    - repo: https://github.com/psf/black
      rev: 23.9.1
      hooks:
          - id: black
            language_version: python3.9
    - repo: https://github.com/pycqa/flake8
      rev: 6.1.0
      hooks:
          - id: flake8
    - repo: https://github.com/awslabs/cfn-python-lint
      rev: v0.80.3
      hooks:
          - id: cfn-lint
            files: template.(yml|yaml)
          - id: cfn-lint
            files: templates/
    - repo: https://github.com/antonbabenko/pre-commit-terraform
      rev: "v1.83.4"
      hooks:
          - id: terraform_fmt
